### ISSUE TITLE
How can I inistall it on Redmine 3.2.X?

### ISSUE THREAD

**Issue by archonwang** [neopoly/redmine-custom_startpage#1]
How can I inistall it on Redmine 3.2.X?
Thanks so much.

**Comment by jnbt** [comment]
Should just work as described in the "Installation" section of the README.md. 

Do you face any particular problems?

**Comment by archonwang** [comment]
@jnbt , Thanks for you reply. I have met a problem that I cannot understand it clearly.
I used redmine 3.2.1 and mysql.
the error log is

> [!] There was an error parsing `Gemfile`: 
> [!] There was an error parsing `Gemfile`: There are no gemspecs at /opt/redmine. Bundler cannot continue.
> 
>  #  from /opt/redmine/plugins/redmine-custom_startpage/Gemfile:4
>  #  -------------------------------------------
>  #  # Specify your gem's dependencies in candy_check.gemspec
> 
> >  gemspec
> >  #  -------------------------------------------
> > . Bundler cannot continue.
> 
>  #  from /opt/redmine/Gemfile:116
>  #  -------------------------------------------
>  #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", **FILE**) do |file|
> 
> >    eval_gemfile file
> >  #  end
> >  #  -------------------------------------------

**Comment by archonwang** [comment]
I make mistake with installation. thanks.
Step1: create a file in Redmine root with name "Gemfile.local"
Step2: write in the file with  
gem "redmine-custom_startpage"
Step3: bundle install
Step4: restart redmine...

Thanks.

**Comment by jnbt** [comment]
Great! Closing now.
